import { FetchPage, Fetch } from "fetch.slint";
import { Utility } from "utils.slint";

export component MainWindow inherits Window {
    title: "bidown-ui";
    min-width: 600px;
    min-height: 400px;

    //////// field ////////

    in-out property <int> page: 0;

    //////// navigate ////////

    HorizontalLayout {
        // 侧边导航栏
        Rectangle {
            width: 60px;
            VerticalLayout {
                spacing: 10px;
                padding: 10px;

                // 下载
                Image {
                    source: @image-url("icons/arrow_download.png");
                    width: 40px;
                    height: 40px;
                    TouchArea {
                        clicked => {
                            page = 0;
                        }
                    }
                }
            }
        }

        //////// content ////////

        // 下载页
        fetch-page := FetchPage {
            width: 100%;
            height: 100%;
            visible: page == 0;
        }
    }
}

//////// export ////////

export { Fetch, Utility }
